import { StaticImage } from "gatsby-plugin-image";
import React from "react";
import { Swiper, SwiperSlide } from "swiper/react";
import { homeSkillSlider } from "../constants/swiperConstants";

const TheyTrustUs = () => {
  return (
    <section className="they-trust-us-section">
      <div className="container">
        <div className="row">
          <div className="col-12">
            <div className="skill-home">
              <h2 className="title">They trust us</h2>
            </div>
          </div>
        </div>
      </div>
      <Swiper className="homeskillslider" {...homeSkillSlider}>
        <div className="swiper-wrapper">
          <SwiperSlide>
            <div>
              <StaticImage
                src={"../images/logos/client-castrol.png"}
                alt="castrol"
                placeholder="tracedSVG"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                src={"../images/logos/client-toi.png"}
                alt="Toi"
                placeholder="tracedSVG"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                src={"../images/logos/client-goeres.jpeg"}
                alt="goeres"
                placeholder="tracedSVG"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                src={"../images/logos/client-firstpost.png"}
                alt="first-post"
                placeholder="tracedSVG"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                src={"../images/logos/client-l-t.jpeg"}
                alt="l-t"
                placeholder="tracedSVG"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                src={"../images/logos/client-flipkart.jpeg"}
                alt="flipkart"
                placeholder="tracedSVG"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                src={"../images/logos/client-latestly.jpeg"}
                alt="client-latestly"
                placeholder="tracedSVG"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                src={"../images/logos/client-teamup.jpeg"}
                alt="client-teamup"
                placeholder="tracedSVG"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                src={"../images/logos/client-ironman.jpg"}
                alt="client-ironman"
                placeholder="tracedSVG"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                src={"../images/logos/5_Ring.png"}
                alt="5_Ring"
                placeholder="tracedSVG"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                src={"../images/logos/2_Emirates.png"}
                alt="2_Emirates"
                placeholder="tracedSVG"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                src={"../images/logos/3_MG.png"}
                alt="3_MG"
                placeholder="tracedSVG"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                src={"../images/logos/7_GMC.png"}
                alt="7_GMC"
                placeholder="tracedSVG"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/7_Chevrolet.png"}
                alt="7_Chevrolet"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/1_Isuzu.png"}
                alt="1_Isuzu"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/6_Royal-Enfield.png"}
                alt="6_Royal-Enfield"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/4_Loreal.png"}
                alt="4_Loreal"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/9_bp.png"}
                alt="9_bp"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/client-vodafone.png"}
                alt="client-vodafone"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/client-ge-money.png"}
                alt="client-ge-money"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/client-audi.png"}
                alt="client-audi"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/client-arcelor.png"}
                alt="client-arcelor"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/client-tomorrow-street.png"}
                alt="tomorrow-street"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/client-cna.png"}
                alt="client-cna"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/client-technoport.png"}
                alt="client-technoport"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/client-chronicle.jpg"}
                alt="client-chronicle"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/client-ey.png"}
                alt="client-ey"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/client-mpay.png"}
                alt="client-mpay"
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div>
              <StaticImage
                placeholder="tracedSVG"
                src={"../images/logos/client-WikiStage.jpg"}
                alt="client-WikiStage"
              />
            </div>
          </SwiperSlide>
        </div>
      </Swiper>
    </section>
  );
};

export default TheyTrustUs;
